create table department (id bigint generated by default as identity, name varchar(255), primary key (id))
create table employee (id bigint generated by default as identity, name varchar(255), department_id bigint, salary numeric(18,2), primary key (id))
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department